export const APP_SET_INITED = 'APP_SET_INITED'
export const APP_SET_USER = 'APP_SET_USER'

export const MIC_SET_THINGS = 'MIC_SET_THINGS'
export const MIC_SET_OBSERVATION = 'MIC_SET_OBSERVATION'
export const MIC_UPDATE_THINGS = 'MIC_UPDATE_THINGS'
export const MIC_UPDATE_OBSERVATION = 'MIC_UPDATE_OBSERVATION'
